blank_issues_enabled: false
contact_links:
  - name: 💬 Discussions / Questions générales
    url: https://github.com/ton-org/ton-repo/discussions
    about: Pour poser des questions, proposer une idée ou discuter.
